---
- hosts: master-manager
  gather_facts: no
  remote_user: root
  tasks:
    - name: Create kube controller manager cert/config
      script: create_kube_controller_manager_cert.sh {{k8s_cert_path}} {{master1}} {{master2}} {{master3}} {{MASTER_VIP}}

    - name: Get kube controller manager cert/config tar
      fetch: src={{k8s_cert_path}}/kube-controller-manager-cert.tar.gz dest=/tmp/ flat=yes

- hosts: master
  gather_facts: no
  remote_user: root
  tasks:
    - name: "Copy kube controller manager cert/config"
      copy: src=/tmp/kube-controller-manager-cert.tar.gz dest={{k8s_cert_path}}/

    - name: "tar zxf kube controller manager cert/config"
      shell: "cd {{k8s_cert_path}}; \
              tar zxf kube-controller-manager-cert.tar.gz; \
              mv kube-controller-manager.kubeconfig {{WORK_DIR}}/k8s/; \
              rm -f kube-controller-manager-cert.tar.gz"

    - name: "Create kube controller manager service"
      template: src=kube-controller-manager.service.template dest=/etc/systemd/system/kube-controller-manager.service

    - name: "Start kube controller manager service"
      systemd: name=kube-controller-manager daemon_reload=yes state=restarted enabled=yes

    - name: "查看输出的 metric"
      shell: "curl -s --cacert {{k8s_cert_path}}/ca.pem https://127.0.0.1:10252/metrics |head"
      register: rs

    - debug: msg="{{rs.stdout_lines}}"